""" Create initial schema

Revision ID: a0643f968144
Revises:
Create Date: 2022-11-04 18:54:26.383684

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a0643f968144"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduled_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("job", sa.Text(), nullable=False),
        sa.Column("triggered_by", sa.Text(), nullable=False),
        sa.Column(
            "date_time",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("account_confirmed", sa.Boolean(), nullable=False),
        sa.Column("password_change_token", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "host_health_check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_reachable", sa.Boolean(), nullable=False),
        sa.Column("output_text", sa.Text(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_job_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_job_id"],
            ["scheduled_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("host_health_check")
    op.drop_table("user")
    op.drop_table("scheduled_job")
    op.drop_table("host")
    # ### end Alembic commands ###
