"""Initial Database

Revision ID: f769380df17e
Revises:
Create Date: 2022-08-06 18:51:44.841236

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f769380df17e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "host",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("account_confirmed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("password_change_token", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "health_check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "date_time",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ping_success", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "host_health_check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("reachable", sa.Boolean(), nullable=False),
        sa.Column("output_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ("host_id",),
            ["health_check.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("host")
    op.drop_table("host_health_check")
    op.drop_table("health_check")
    # ### end Alembic commands ###
