# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "."

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Dependencies
        run: poetry install

      - name: Run Unit Tests
        run: poetry run pytest tests/test/unit

      - name: Run migrations
        run: psql -f tests/database/init_e2e_database.sql postgresql://postgres:postgres@localhost:5432/postgres

      - name: Run e2e Tests
        run: poetry run pytest tests/test/e2e
